services:
  - type: web
    name: soccer-events-pwa
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_BASE_URL
        value: https://soccer-events-pwa.onrender.com
